### ISSUE TITLE
Integrate functionality from `PYMC_GPflow_CSF3sampler_step2.sh`

### ISSUE THREAD

**Issue by gcapes** [RoryAtBar/Abaqus_bayesian_matflow#25]

**Comment by gcapes** [comment]
I've got most of the code ready to go (I think), but need to check subsequent steps to see whether a MatFlow sequence would be useful, or a series of output files in the same directory (currently `f"Idata_chain_{JobID}.nc"`)

**Comment by gcapes** [comment]
Currently struggling with relative import of the refactored normaliser code, and also understanding how we get multiple netcdf files when that part of the code doesn't appear to be in a loop...?

**Comment by gcapes** [comment]
Turns out I didn't need to do the refactor after all, as the normaliser code is only used in the data set up step anyway. So I've put the code back how it was which side steps the import error.

**Comment by gcapes** [comment]
Oh yes! The original script is a job array, hence the multiple netcdf files.

**Comment by gcapes** [comment]
I'm currently following the original code, but have a bit of a messy hack where I'm loading a model file from the execute directory using a `model_name` string ( = `Quadplast_timesteps_5-15`) to build the file name.
I'm not sure this is needed/useful, and might be better to just use something like `gp_model.pkl`, saved to the artifacts directory.

**Comment by gcapes** [comment]
That doesn't work, I think because there is no longer an obvious dependence between the tasks, so MatFlow can execute them out of order. I could save the file as a command file, but that wouldn't signal a dependency because MatFlow can't pass files around.

For now I guess I'll need to pass a dummy variable in order to set the dependency? I can't see another way to do it.

**Comment by gcapes** [comment]
That seems to work, but now I've this error, which I think is because I removed the normaliser class from this file, as it didn't look to be used. I guess it is, though I don't understand how:
```
Traceback (most recent call last):
  File "/net/scratch2/mbexegc2/Abaqus_bayesian_matflow/step2/execute/task_4_sample_model/e_0/r_0/sample_model.py", line 335, in <module>
    sample_model(**direct_ins)
  File "/net/scratch2/mbexegc2/Abaqus_bayesian_matflow/step2/execute/task_4_sample_model/e_0/r_0/sample_model.py", line 50, in sample_model
    x = pickle.load(unpick)
        ^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'Normaliser' on <module '__main__' from '/net/scratch2/mbexegc2/Abaqus_bayesian_matflow/step2/execute/task_4_sample_model/e_0/r_0/sample_model.py'>
```

**Comment by gcapes** [comment]
Well adding it back in has fixed it, but I don't understand why.
